#include <immintrin.h>
#include <stdio.h>
#include <chrono>
#include <random>

// 8個の32ビット状態を同時に更新する
static __m256i xorshift32x8(__m256i state)
{
    state = _mm256_xor_si256(
        state,
        _mm256_slli_epi32(state, 13)
    );

    state = _mm256_xor_si256(
        state,
        _mm256_srli_epi32(state, 17)
    );

    state = _mm256_xor_si256(
        state,
        _mm256_slli_epi32(state, 5)
    );

    return state;
}

float estimate_integral_simd(const int sample_count, const float interval_min, const float interval_max) {
    constexpr int simd_len = sizeof(__m256) / sizeof(float); // 8 lanes for AVX
    const float interval_width = interval_max - interval_min;
    __m256i random_state = _mm256_setr_epi32(
        123456789,
        362436069,
        521288629,
        88675123,
        5783321,
        6615241,
        9983651,
        1234567
    );
	const __m256 min_vector = _mm256_set1_ps(interval_min);
	const __m256 width_vector = _mm256_set1_ps(interval_width);
	// 2^24 = 16777216.0f
	const __m256 random_scale = _mm256_set1_ps(1.0f / 16777216.0f); // Scale to [0, 1)
    __m256 sum = _mm256_setzero_ps();
    for (int i = 0; i < sample_count; i += simd_len) {
		random_state = xorshift32x8(random_state);
		// 32 bit random integers in [0, 2^32-1] are generated by xorshift32x8
		// convert to float in [0, 1) by scaling with 1.0f / 2^24 because float has 24 bits
		// So we need to shift right by 8 bits to get the top 24 bits of the random integer
		const __m256i random_integer = _mm256_srli_epi32(random_state, 8);
		const __m256 random_01 = _mm256_mul_ps(_mm256_cvtepi32_ps(random_integer), random_scale);
        // x = interval_min + random_01 * interval_width
		const __m256 x = _mm256_add_ps(min_vector, _mm256_mul_ps(random_01, width_vector));
        const __m256 fx = _mm256_mul_ps(random_01, random_01); // fx = x^2
        sum = _mm256_add_ps(sum, fx); // sum += fx
    }
    float lanes[simd_len];
    _mm256_storeu_ps(lanes, sum);
    float total = 0.0f;
    for (int i = 0; i < simd_len; ++i) {
        total += lanes[i];
    }
    return interval_width * total / sample_count;
}

static uint32_t xorshift32(uint32_t& state)
{
    state ^= state << 13;
    state ^= state >> 17;
    state ^= state << 5;

    return state;
}

float estimate_integral_scalar(
    const int sample_count,
    const float interval_min,
    const float interval_max)
{
    const float interval_width =
        interval_max - interval_min;

    // xorshift32では0を初期状態にしてはいけない
    uint32_t random_state = 123456789u;

    // 2^24
    constexpr float random_scale =
        1.0f / 16777216.0f;

    float sum = 0.0f;

    for (int i = 0; i < sample_count; ++i) {
        // 前回の状態から、次の32ビット状態を作る
        const uint32_t random_bits =
            xorshift32(random_state);

        // 上位24ビットを取り出す
        const uint32_t random_integer =
            random_bits >> 8;

        // 0 ～ 2^24-1 を [0, 1) のfloatへ変換
        const float random_01 =
            static_cast<float>(random_integer)
            * random_scale;

        // [0, 1) から積分区間へ変換
        const float x =
            interval_min
            + random_01 * interval_width;

        const float fx = x * x;

        sum += fx;
    }

    return interval_width
        * sum
        / static_cast<float>(sample_count);
}

int main(void) {
	constexpr int simd_len = sizeof(__m256) / sizeof(float); // 8 lanes for AVX
    constexpr int sample_count = simd_len * (10240000 / 8);
    constexpr float interval_min = 0.0f;
    constexpr float interval_max = 1.0f;
    constexpr float interval_width = interval_max - interval_min;
    constexpr float exact = 1.0f / 3.0f;

    static_assert(sample_count % simd_len == 0);

	auto _start = std::chrono::high_resolution_clock::now();
	const float result_simd = estimate_integral_simd(sample_count, interval_min, interval_max);
	const auto simd_duration = std::chrono::high_resolution_clock::now() - _start;
	_start = std::chrono::high_resolution_clock::now();
	const float result_scalar = estimate_integral_scalar(sample_count, interval_min, interval_max);
	const auto scalar_duration = std::chrono::high_resolution_clock::now() - _start;

    printf("Monte Carlo integration with SIMD\n");
    printf("Integral: int_0^1 x^2 dx\n");
    printf("Samples: %d\n", sample_count);
    printf("SIMD Calculation Time: %.3f ms\n", std::chrono::duration<double, std::milli>(simd_duration).count());
	printf("Scalar Calculation Time: %.3f ms\n", std::chrono::duration<double, std::milli>(scalar_duration).count());
    printf("Exact:    %.8f\n", exact);
    printf("SIMD Error:    %.8e\n", result_simd - exact);
    printf("Scalar Error:    %.8e\n", result_scalar - exact);

    return 0;
}
